export const ROLES = {
    ADMIN: 'ADMIN',
    OPERATIONS: 'OPERATIONS',
    SALES: 'SALES'
}

export const WORK_ORDER_STATUSES = ['ASSIGNED', 'IN_PROGRESS', 'COMPLETED']
export const TRANSFER_STATUSES = ['REQUESTED', 'DISPATCHED', 'RECEIVED']
export const ORDER_STATUSES = ['PENDING', 'RESERVED', 'COMPLETED', 'CANCELLED']
